// -----------------------------------------------------------------------
// Datos NO traducibles del portafolio: nombre, ubicación, links, tech
// stack, contacto. El texto que cambia con el idioma (títulos, textos de
// botones, descripciones) vive en lib/translations.js.
// Edita este archivo para actualizar tus proyectos, skills y contacto.
// -----------------------------------------------------------------------

export const profile = {
  name: "Miguel Chavez",
  location: "Lima, Perú",
};

// Categorías de proyectos. accent: "amber" para trabajo ya construido,
// "mint" para ciencia de datos. Las etiquetas visibles (label/shortLabel)
// viven en lib/translations.js, indexadas por este mismo id.
export const projectCategories = [
  { id: "saas", accent: "amber" },
  { id: "web", accent: "amber" },
  { id: "data", accent: "mint" },
];

export const projects = [
  {
    category: "saas",
    title: "Lynksit",
    description: {
      es: "Plataforma SaaS B2B para pequeños negocios en Latinoamérica: catálogos de producto integrados a WhatsApp y automatización de ventas con agentes de IA configurables por tipo de industria.",
      en: "B2B SaaS platform for small businesses in Latin America: product catalogs integrated with WhatsApp and sales automation with AI agents configurable by industry.",
    },
    tech: ["React", "Vite", "Node.js", "Express", "Supabase"],
    github: "https://github.com/tu-usuario/lynksit",
    demo: "https://lynksit.app",
    featured: true,
    status: null,
  },
  {
    category: "web",
    title: "Proyecto Dos",
    description: {
      es: "Describe aquí el problema que resuelve, tu rol y el resultado obtenido. Sé específico: métricas o impacto real generan más confianza que adjetivos.",
      en: "Describe here the problem it solves, your role, and the outcome. Be specific: real metrics or impact build more trust than adjectives.",
    },
    tech: ["Next.js", "TypeScript", "PostgreSQL"],
    github: "https://github.com/tu-usuario/proyecto-dos",
    demo: "",
    featured: false,
    status: null,
  },
  {
    category: "web",
    title: "Proyecto Tres",
    description: {
      es: "Otra pieza de tu portafolio. Reemplaza este texto con un caso real cuando lo tengas listo para publicar.",
      en: "Another piece of your portfolio. Replace this text with a real case study once it's ready to publish.",
    },
    tech: ["React", "Supabase", "Tailwind CSS"],
    github: "https://github.com/tu-usuario/proyecto-tres",
    demo: "",
    featured: false,
    status: null,
  },
  {
    category: "data",
    title: "Panel de métricas de ventas",
    description: {
      es: "Dashboard en desarrollo para analizar conversión y comportamiento de clientes a partir de los datos generados por Lynksit.",
      en: "Dashboard in progress to analyze conversion and customer behavior from the data generated by Lynksit.",
    },
    tech: ["Python", "SQL", "Pandas"],
    github: "",
    demo: "",
    featured: false,
    status: { es: "En construcción", en: "In progress" },
  },
  {
    category: "data",
    title: "Modelo de segmentación de clientes",
    description: {
      es: "Clasificación de negocios según patrones de uso, pensado para priorizar soporte y detectar riesgo de cancelación (churn).",
      en: "Business classification based on usage patterns, designed to prioritize support and flag churn risk.",
    },
    tech: ["Python", "scikit-learn", "SQL"],
    github: "",
    demo: "",
    featured: false,
    status: { es: "Planeado", en: "Planned" },
  },
  {
    category: "data",
    title: "Reportes automatizados",
    description: {
      es: "Pipeline para generar reportes periódicos de negocio directamente desde Supabase hacia dashboards interactivos.",
      en: "Pipeline to generate periodic business reports straight from Supabase into interactive dashboards.",
    },
    tech: ["Python", "SQL", "Looker Studio"],
    github: "",
    demo: "",
    featured: false,
    status: { es: "Planeado", en: "Planned" },
  },
];

// name: proyecto notable, sin traducción. category: clave usada por
// lib/translations.js (skills.categories) para mostrar el nombre traducido.
export const skills = [
  { name: "React", category: "frontend" },
  { name: "Next.js", category: "frontend" },
  { name: "Tailwind CSS", category: "frontend" },
  { name: "JavaScript / TypeScript", category: "frontend" },
  { name: "Node.js", category: "backend" },
  { name: "Express", category: "backend" },
  { name: "Supabase", category: "backend" },
  { name: "PostgreSQL", category: "backend" },
  { name: "REST APIs", category: "backend" },
  { name: "Python", category: "data" },
  { name: "SQL", category: "data" },
  { name: "Pandas", category: "data" },
  { name: "Git / GitHub", category: "tools" },
  { name: "Vercel", category: "tools" },
  { name: "Railway", category: "tools" },
];

export const contact = {
  email: "tu-correo@ejemplo.com",
  github: "https://github.com/tu-usuario",
  linkedin: "https://linkedin.com/in/tu-usuario",
  whatsapp: "https://wa.me/51900000000",
};
